### ISSUE TITLE
setting duration time, defaults to 1:00

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/NA-Meeting-List-Administrator#2]
when trying to change the duration of a meeting with the NA Administrator app, after hitting save and going back to it the time reverts to 1:00.

this is what i get in my GetChanges report after trying to change a meeting from 1:30 hours to 2:00 hours
`The meeting duration was changed from "1:30" to "2:118"`

and then trying to change it back to 1:30 hours from that

`The meeting duration was changed from "0:00" to "1:89"`

**Comment by pjaudiomv** [comment]
seems in the first example, which displays `2:118` 118 is 60(mins) X2hrs (120) -2 (amount of hours)
same for second `1:89` 89 is 60 x 1.5hrs (90) - 1 (amount of hours)

**Comment by pjaudiomv** [comment]
@LittleGreenViper @bmltguy If you could try and take a look at this before next release that would be super. I'm not too worried about the state or county dropdowns/UIPicker but this directly affects usability alot worse than those. I have tested this with root server versions back to 2.12.2 and the duration is not saving correctly.

**Comment by pjaudiomv** [comment]
line 449 seems suspect here, but i have no idea.

https://github.com/pjaudiomv/BMLTiOSLib/blob/0585629c1f4e2099b0f9a6542df68b97f48c859b/BMLTiOSLib/Framework%20Project/Classes/BMLTiOSLibEditableMeetingNode.swift#L447-L450

**Comment by pjaudiomv** [comment]
```
            if 1440 > newValue {    // Can't be more than 23:59
                let hours = Int(newValue / 60)
                let minutes = newValue - hours
                self.rawMeeting["duration_time"] = String(format: "%02d:%02d:00", hours, minutes)
```
getting our hour by dividing minutes by 60 makes total sense ha
but im just looking at it so say

`newValue = 120`
let hours = 2  `let hours = Int(newValue / 60)= Int(newValue / 60)` <-- cool
let minutes = 118 `let minutes = newValue - hours`                      <--  not cool 
so now ` self.rawMeeting["duration_time"] ` would return 2:118  <-- not cool 

which im guessing is how I got `2:118` when trying to chnage a meeting from `1:30` to `2:00`

**Comment by pjaudiomv** [comment]
maybe instead `let minutes = Int(newValue % 60)`

**Comment by pjaudiomv** [comment]
that probably wouldn't account for when minutes are below 10 as then a leading zero must be added

**Comment by pjaudiomv** [comment]
if padding could be added to string format could do that, or something like this `minutes < 10 ? "0" + minutes : minutes`

**Comment by LittleGreenViper** [comment]
Should be -(2 * 60) (That's how you strip the hours out).
That's a bug.

**Comment by LittleGreenViper** [comment]
In fact, I found another place where I screwed that up.
That's the kind of bug complete unit testing would have caught...
The next releases of the apps will feature the fix, but they won't come out until I've had them tested.

**Comment by LittleGreenViper** [comment]
Can you give me an HTTPS URI I can point to to test?

**Comment by pjaudiomv** [comment]
you mean just the bmlt endpoint where those meeting changes existed

**Comment by LittleGreenViper** [comment]
Yeah. The format already took care of adding padding. That's what that "%02d" was.

**Comment by pjaudiomv** [comment]
https://www.nerna.org/main_server/client_interface/json/?switcher=GetChanges&start_date=2018-12-25&end_date=2018-12-28&service_body_id=8

theres one

**Comment by pjaudiomv** [comment]
meeting id 505, is that what you wanted or something else

**Comment by pjaudiomv** [comment]
https://latest.aws.bmlt.app/main_server/client_interface/json/?switcher=GetChanges&meeting_id=693
you could always use this server too, i just created user chrism and your default test pass. but all the users are that pass

**Comment by LittleGreenViper** [comment]
I'm using that server. I checked the change history for meeting ID 693.
How can I reproduce the bug?

**Comment by pjaudiomv** [comment]
oh sorry, just log into the na administrator app to that server, edit a meeting. then change the duration and hit save. for example if the duration is an hour and you change it to two hours it should reproduce the same results as meeting ID 693.
Before `duration_time | "01:00:00"`
After `duration_time | "02:118:00"`

**Comment by LittleGreenViper** [comment]
I'm looking at it now. I tried changing a meeting from 1 hour to 2 hours, and it stayed at 1 hour. However, I'm not yet sure if the issue happened on the server or in my software. It seems to be hung right now on the first meeting when you log in as gnyr_admin (Hope by the Harbor). I clicked on "View Change History," and it is hung like John Holmes. However, I am also using the simulator, which can be quite slow.

**Comment by LittleGreenViper** [comment]
Actually, I may have borked the server. Everything is hung.

**Comment by LittleGreenViper** [comment]
Nah. It was me, but I'm not seeing any change at all. 1 hour stays 1 hour.

**Comment by pjaudiomv** [comment]
Yea the app itself will stay at 1 hour because that's default and it doesn't like what it's receiving. Same with the BMLT admin however the change log displays what's actually being stored

**Comment by LittleGreenViper** [comment]
And that's where I keep getting hung.
I may need to look at this more in the morning.

**Comment by LittleGreenViper** [comment]
I'm not hanging anymore, but I'm also not seeing the fix I added.
I hate CocoaPods. It's severely messing me up.

**Comment by pjaudiomv** [comment]
yea certainly no rush its not going any where ha. If you need more help testing or diagnosing let me know.

**Comment by LittleGreenViper** [comment]
I'lll get it. I'm like the Mounties: I always get my bug.
Testing a CocoaPod in a target is a challenge. I can only use its test harness, then publish it on blind faith, and hope that its fixed when I import it.

Yuck.

**Comment by LittleGreenViper** [comment]
I'm pretty sure I got it. That was an ugly bug. Thanks for finding it.
I'll publish it in the CocoaPod, and import it into the admin app, and see if that works.

**Comment by pjaudiomv** [comment]
yea luckily nothings pulling from that in real time. still not a great way to test.

**Comment by pjaudiomv** [comment]
cool, yea first I thought I was crazy, then I was worried a change we made to root server caused it. but after checking older versions of root server i knew it had to be in there

**Comment by pjaudiomv** [comment]
sweet I was able to get test env set up properly with correct pod versions and this seems to be working fine now. Duration is being shown and set properly.

**Comment by pjaudiomv** [comment]
Tested Face ID as well seems to be working.

**Comment by pjaudiomv** [comment]
I don't trust these simulators, have to wait for test flight as well.

**Comment by LittleGreenViper** [comment]
Good show!
We'll make an iOS developer out of you yet.
The simulators are pretty damn good, but not perfect. They are "simulators," as opposed to "emulators" (what Android Studio uses). This means they run with native x64 code on the Mac (not a VM running ARM code).
99% of the time, it's fine, but you can get weird issues in the corners.
If you want to run on your device, you need to pay Apple $99 (which is peanuts, but keeps the Chinese hackers down to a dull roar).

**Comment by pjaudiomv** [comment]
I believe this has been fixed and is in last release
