### ISSUE TITLE
Deleted meetings not loading

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/NA-Meeting-List-Administrator#5]
no meetings come up or error appears

**Comment by ChrisMarshallNY** [comment]
I can't reproduce it, here. It may be a server issue.

If you can create a temporary account for me on a server that exposes the issue, I would be grateful.

**Comment by ChrisMarshallNY** [comment]
Not to say that the fix needs to be in the server, mind you. Maybe I need to deal with an anomalous situation better.

**Comment by pjaudiomv** [comment]
closing this, only addition I could see is a feature request to limit response to only look for deleted meetings within a specific date.

**Comment by ChrisMarshallNY** [comment]
[You can already do that](https://bmlt.app/semantic/semantic-changes/). I don’t do it in the app. Mostly because I didn’t want to deal with the UI to do it.
